services:

  frontend:
    build:
      context: ./frontend/Vyanix-React
      args:
        - NEXT_PUBLIC_API_BASE_URL=http://backend:8080/api
    container_name: ecommerce_frontend
    ports:
      - "3000:3000"
    depends_on:
      backend:
        condition: service_healthy
    restart: always
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:3000"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  backend:
    build: ./backend/vyanix-webservice
    container_name: ecommerce_backend
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:6543/postgres
      - SPRING_DATASOURCE_USERNAME=postgres.pktrqykpjbwxbadgceor
      - SPRING_DATASOURCE_PASSWORD=Supabase#Vyanix@2026
      - REDIS_HOST=redis
      - MEILI_HOST=http://meilisearch:7700
    depends_on:
      redis:
        condition: service_started
      meilisearch:
        condition: service_started
    restart: always
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s

  nginx:
    image: nginx:latest
    container_name: ecommerce_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      frontend:
        condition: service_healthy
      backend:
        condition: service_healthy
    restart: always
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:80"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

  redis:
    image: redis:7
    container_name: ecommerce_redis
    ports:
      - "6379:6379"
    restart: always

  meilisearch:
    image: getmeili/meilisearch
    container_name: ecommerce_meilisearch
    ports:
      - "7700:7700"
    environment:
      - MEILI_NO_ANALYTICS=true
    volumes:
      - ./data/meilisearch:/meili_data
    restart: always
