version: "3.9"

services:

  frontend:
    build:
      context: ./frontend/Vyanix-React
      args:
        - NEXT_PUBLIC_API_BASE_URL=http://backend:8080/api
    container_name: ecommerce_frontend
    ports:
      - "3000:3000"
    restart: always

  backend:
    build: ./backend/vyanix-webservice
    container_name: ecommerce_backend
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:6543/postgres
      - SPRING_DATASOURCE_USERNAME=postgres.pktrqykpjbwxbadgceor
      - SPRING_DATASOURCE_PASSWORD=Supabase#Vyanix@2026
      - REDIS_HOST=redis
      - MEILI_HOST=http://meilisearch:7700
    depends_on:
      - redis
      - meilisearch
    restart: always

  nginx:
    image: nginx:latest
    container_name: ecommerce_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    restart: always

  redis:
    image: redis:7
    container_name: ecommerce_redis
    ports:
      - "6379:6379"
    restart: always

  meilisearch:
    image: getmeili/meilisearch
    container_name: ecommerce_meilisearch
    ports:
      - "7700:7700"
    environment:
      - MEILI_NO_ANALYTICS=true
    volumes:
      - ./data/meilisearch:/meili_data
    restart: always
